# Generated by Django 3.0.2 on 2020-02-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20200207_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='comp_emp_strength',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='positions_to_fill',
            field=models.BigIntegerField(null=True),
        ),
    ]
