# Generated by Django 3.0.2 on 2020-02-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailengine', '0002_auto_20200131_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('New Lead', 'New Lead'), ('Lead Status Change', 'Lead Status Change'), ('Lead Reassigned', 'Lead Reassigned'), ('Regular Follow up', 'Regular Follow up'), ('Escalation', 'Escalation')], max_length=255, verbose_name='Type of Event'),
        ),
    ]
