# Generated by Django 3.0.2 on 2020-02-09 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailengine', '0004_auto_20200209_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lead_assigned_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
